CREATE TABLE Students (ID INTEGER PRIMARY KEY, NAME TEXT, CITY TEXT, BIRTH INTEGER);
DROP TABLE Students

INSERT INTO Students VALUES (1, 'SHALOM', 'TEL AVIV ', 1974);
INSERT INTO Students VALUES (2, 'YURI','RAANANA', 1980);
INSERT INTO Students VALUES (3, 'ANAT', 'RISHON', 1994);
INSERT INTO Students VALUES (4, 'DANA', 'REHOVOT', 1990);
INSERT INTO Students VALUES (5, 'OMER', 'JERUSALEM', 1987);

ALTER TABLE Students ADD COLUMN GRADE INTEGER

UPDATE Students SET GRADE=95 WHERE id=1;
UPDATE Students SET GRADE=70 WHERE id=2;
UPDATE Students SET GRADE=85 WHERE id=3;
UPDATE Students SET GRADE=99 WHERE id=4;
UPDATE Students SET GRADE=91 WHERE id=5;

SELECT * FROM Students

SELECT NAME, GRADE FROM Students

SELECT AVG (GRADE) FROM Students

ALTER TABLE Students ADD COLUMN EXCELLENT 
UPDATE Students SET EXCELLENT = 'YES' WHERE GRADE > 90
UPDATE Students SET EXCELLENT = 'NO' WHERE GRADE <= 90
